'\" t
.\"     Title: os-release
.\"    Author: Lennart Poettering <lennart@poettering.net>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2011
.\"    Manual: os-release
.\"    Source: systemd
.\"  Language: English
.\"
.TH "OS\-RELEASE" "5" "06/16/2011" "systemd" "os-release"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
os-release \- Operating system identification
.SH "SYNOPSIS"
.PP
/etc/os\-release
.SH "DESCRIPTION"
.PP
The
/etc/os\-release
file contains operating system identification data\&.
.PP
The basic file format of
os\-release
is a newline\-separated list of environment\-like shell\-compatible variable assignments\&. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments no shell features are supported, allowing applications to read the file without implementing a shell compatible execution engine\&.
.PP
/etc/os\-release
contains data that is defined by the operating system vendor and should not be changed by the administrator\&.
.PP
Depending on the operating system other configuration files might be checked for OS identification as well, however only as fallback\&.
.SH "OPTIONS"
.PP
The following OS identifications parameters may be set using
/etc/os\-release:
.PP
\fINAME=\fR
.RS 4
A string identifying the operating system, without a version string, and not necessarily suitable for presentation to the user\&. If not set defaults to
Linux\&. Example:
NAME=Fedora
or
NAME="Debian GNU/Linux"\&.
.RE
.PP
\fIVERSION=\fR
.RS 4
A string identifying the operating system version, excluding any name information and suitable for presentation to the user\&. Example:
VERSION=15
or
VERSION="15 (Rawhide)"\&.
.RE
.PP
\fIID=\fR
.RS 4
A lower\-case string (no spaces) identifying the operating system, excluding any version information and suitable for processing by scripts or usage in generated file names\&. If not set defaults to
linux\&. Example:
ID=fedora\&.
.RE
.PP
\fIVERSION_ID=\fR
.RS 4
A lower\-case string (mostly numeric, no spaces) identifying the operating system version, excluding any name information and suitable for processing by scripts or usage in generated file names\&. Example:
VERSION_ID=15\&.
.RE
.PP
\fIPRETTY_NAME=\fR
.RS 4
A pretty operating system name in a format suitable for presentation to the user\&. May or may not contain an OS version of some kind, as suitable\&. If not set defaults to
Linux\&. Example:
PRETTY_NAME=Fedora 15 (Rawhide)\&.
.RE
.PP
\fIANSI_COLOR=\fR
.RS 4
A suggested presentation color when showing the distribution name on the console\&. This should be specified as string suitable for inclusion in the ESC [ m ANSI/ECMA\-48 escape code for setting graphical rendition\&. Example:
ANSI_COLOR=0;31
for red, or
ANSI_COLOR=1;34
for light blue\&.
.RE
.PP
If you are reading this file from code or a shell script to determine the OS or a specific version of it, use the ID and VERSION_ID fields\&. When looking for an OS identification string for presentation to the user use the PRETTY_NAME field\&.
.PP
Note that operating system vendors may choose not to provide version information, for example to accommodate for rolling releases\&. In this case VERSION and VERSION_ID may be unset\&. Applications should not rely on these fields to be set\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
NAME=Fedora
VERSION="15 (Rawhide)"
ID=fedora
VERSION_ID=15
PRETTY_NAME="Fedora 15 (Rawhide)"
ANSI_COLOR=0;34
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP

\fBsystemd\fR(1),
\fBlsb_release\fR(1),
\fBhostname\fR(5),
\fBmachine-id\fR(5),
\fBmachine-info\fR(5)
.SH "AUTHOR"
.PP
\fBLennart Poettering\fR <\&lennart@poettering\&.net\&>
.RS 4
Developer
.RE
