'\" t
.\"     Title: systemd-journald.conf
.\"    Author: Lennart Poettering <lennart@poettering.net>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/16/2012
.\"    Manual: systemd-journald.conf
.\"    Source: systemd
.\"  Language: English
.\"
.TH "SYSTEMD\-JOURNALD\&." "5" "03/16/2012" "systemd" "systemd-journald.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-journald.conf \- Journal service configuration file
.SH "SYNOPSIS"
.PP
systemd\-journald\&.conf
.SH "DESCRIPTION"
.PP
This files configures various parameters of the systemd journal service\&.
.SH "OPTIONS"
.PP
All options are configured in the
[Journal]
section:
.PP
\fICompress=\fR
.RS 4
Takes a boolean value\&. If enabled (the default) data objects that shall be stored in the journal and are larger than a certain threshold are compressed with the XZ compression algorithm before they are written to the file system\&.
.RE
.PP
\fIRateLimitInterval=\fR, \fIRateLimitBurst=\fR
.RS 4
Configures the rate limiting that is applied to all messages generated on the system\&. If in the time interval defined by
\fIRateLimitInterval=\fR
more messages than specified in
\fIRateLimitBurst=\fR
are logged by a service all further messages within the interval are dropped, until the interval is over\&. A message about the number of dropped messages is generated\&. This rate limiting is applied per\-service, so that two services which log do not interfere with each other\*(Aqs limit\&. Defaults to 100 messages in 10s\&. The time specification for
\fIRateLimitInterval=\fR
may be specified in the following units:
s,
min,
h,
ms,
us\&. To turn off any kind of rate limiting, set either value to 0\&.
.RE
.PP
\fISystemMaxUse=\fR, \fISystemKeepFree=\fR, \fISystemMaxFileSize=\fR, \fISystemMinFileSize=\fR, \fIRuntimeMaxUse=\fR, \fIRuntimeKeepFree=\fR, \fIRuntimeMaxFileSize=\fR, \fIRuntimeMinFileSize=\fR
.RS 4
Enforce size limits on the journal files stored\&. The options prefixed with
System
apply to the journal files when stored on a persistant file system, more specifically
/var/log/journal\&. The options prefixed with
Runtime
apply to the journal files when stored on a volatile in\-memory file system, more specifically
/run/log/journal\&. The former is used only when
/var
is mounted, writable and the directory
/var/log/journal
exists\&. Otherwise only the latter applies\&. Note that this means that during early boot and if the administrator disabled persistant logging only the latter options apply, while the former apply if persistant logging is enabled and the system is fully booted up\&.
\fISystemMaxUse=\fR
and
\fIRuntimeMaxUse=\fR
control how much disk space the journal may use up at maximum\&. Defaults to 10% of the size of the respective file system\&.
\fISystemKeepFree=\fR
and
\fIRuntimeKeepFree=\fR
control how much disk space the journal shall always leave free for other uses if less than the disk space configured in
\fISystemMaxUse=\fR
and
\fIRuntimeMaxUse=\fR
is available\&. Defaults to 5% of the size of the respective file system\&.
\fISystemMaxFileSize=\fR
and
\fIRuntimeMaxFileSize=\fR
control how large individual journal files may grow at maximum\&. This influences the granularity in which disk space is made available through rotation, i\&.e\&. deletion of historic data\&. Defaults to one eigth of the values configured with
\fISystemMaxUse=\fR
and
\fIRuntimeMaxUse=\fR, so that usually seven rotated journal files are kept as history\&.
\fISystemMinFileSize=\fR
and
\fIRuntimeMinFileSize=\fR
control how large individual journal files grow at minimum\&. Defaults to 64K\&. Specify values in bytes or use K, M, G, T, P, E as units for the specified sizes\&. Note that size limits are enforced synchronously to journal files as they are extended, and need no explicit rotation step triggered by time\&.
.RE
.PP
\fIForwardToSyslog=\fR, \fIForwardToKMsg=\fR, \fIForwardToConsole=\fR
.RS 4
Control whether log messages received by the journal daemon shall be forwarded to a traditional syslog daemon, to the kernel log buffer (kmsg), or to the system console\&. These options take boolean arguments\&. If forwarding to syslog is enabled but no syslog daemon is running the respective option has no effect\&. By default only forwarding to syslog is enabled\&. These settings may be overriden at boot time with the kernel command line options
systemd_journald\&.forward_to_syslog=,
systemd_journald\&.forward_to_kmsg=
and
systemd_journald\&.forward_to_console=\&. If forwarding to the kernel log buffer and
\fIImportKernel=\fR
is enabled at the same time care is taken to avoid logging loops\&. It is safe to use these options in combination\&.
.RE
.PP
\fIImportKernel=\fR
.RS 4
Controls whether kernel log messages shall be stored in the journal\&. Takes a boolean argument and defaults to enabled\&. Note that currently only one userspace service can read kernel messages at a time, which means that kernel log message reading might get corrupted if it is enabled in more than one service, for example in both the journal and a traditional syslog service\&.
.RE
.SH "SEE ALSO"
.PP

\fBsystemd\fR(1),
\fBsystemd-journalctl\fR(1),
\fBsystemd.conf\fR(5)
.SH "AUTHOR"
.PP
\fBLennart Poettering\fR <\&lennart@poettering\&.net\&>
.RS 4
Developer
.RE
