'\" t
.\"     Title: tmpfiles.d
.\"    Author: Brandon Philips <brandon@ifup.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/01/2011
.\"    Manual: tmpfiles.d
.\"    Source: systemd
.\"  Language: English
.\"
.TH "TMPFILES\&.D" "5" "03/01/2011" "systemd" "tmpfiles.d"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tmpfiles.d \- Configuration for creation, deletion and cleaning of volatile and temporary files
.SH "SYNOPSIS"
.PP
/etc/tmpfiles\&.d/*\&.conf
.SH "DESCRIPTION"
.PP
\fBsystemd\-tmpfiles\fR
uses the configuration files in
/etc/tmpfiles\&.d/
to describe the creation, cleaning and removal of volatile and temporary files and directories which usually reside in directories such as
/var/run
or
/tmp\&. Each configuration file is named in the style of
/etc/tmpfiles\&.d/<program>\&.conf\&.
.SH "CONFIGURATION FORMAT"
.PP
The configuration format is one line per path containing action, mode, ownership and age fields:
.sp
.if n \{\
.RS 4
.\}
.nf
Type Path          Mode UID  GID  Age
d    /var/run/user 0755 root root 10d
.fi
.if n \{\
.RE
.\}
.SS "Type"
.PP
\fIf\fR
.RS 4
Create a file if it doesn\*(Aqt exist yet
.RE
.PP
\fIF\fR
.RS 4
Create or truncate a file
.RE
.PP
\fId\fR
.RS 4
Create a directory if it doesn\*(Aqt exist yet
.RE
.PP
\fID\fR
.RS 4
Create or empty a directory
.RE
.PP
\fIx\fR
.RS 4
Ignore a path during cleaning\&. Use this type to exclude paths from clean\-up as controlled with the Age parameter\&. Note that lines of this type do not influence the effect of r or R lines\&. Lines of this type accept shell\-style globs in place of of normal path names\&.
.RE
.PP
\fIr\fR
.RS 4
Remove a file or directory if it exists\&. This may not be used to remove non\-empty directories, use R for that\&. Lines of this type accept shell\-style globs in place of normal path names\&.
.RE
.PP
\fIR\fR
.RS 4
Recursively remove a path and all its subdirectories (if it is a directory)\&. Lines of this type accept shell\-style globs in place of normal path names\&.
.RE
.SS "Mode"
.PP
The file access mode to use when creating this file or directory\&. If omitted or when set to \- the default is used: 0755 for directories, 0644 for files\&. This parameter is ignored for x, r, R lines\&.
.SS "UID, GID"
.PP
The user and group to use for this file or directory\&. This may either be a numeric user/group ID or a user or group name\&. If omitted or when set to \- the default 0 (root) is used\&. \&. These parameters are ignored for x, r, R lines\&.
.SS "Age"
.PP
The date field, when set, is used to decide what files to delete when cleaning\&. If a file or directory is older than the current time minus the age field it is deleted\&. The field format is a series of integers each followed by one of the following postfixes for the respective time units:
.PP
\fIs\fR, \fImin\fR, \fIh\fR, \fId\fR, \fIw\fR, \fIms\fR, \fIm\fR, \fIus\fR
.RS 4
.RE
.PP
If multiple integers and units are specified the time values are summed up\&.
.PP
The age field only applies to lines starting with d, D and x\&. If omitted or set to \- no automatic clean\-up is done\&.
.SH "EXAMPLE"
.PP
\fBExample\ \&1.\ \&/etc/tmpfiles.d/screen.conf example\fR
.PP
\fBscreen\fR
needs two directories created at boot with specific modes and ownership\&.
.sp
.if n \{\
.RS 4
.\}
.nf
d /var/run/screens 1777 root root 10d
d /var/run/uscreens 0755 root root 10d12h
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP

\fBsystemd\fR(1),
\fBsystemd-tmpfiles\fR(8)
.SH "AUTHOR"
.PP
\fBBrandon Philips\fR <\&brandon@ifup\&.org\&>
.RS 4
Documentation
.RE
