/* ask-password-agent.c generated by valac 0.9.7, the Vala compiler
 * generated from ask-password-agent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <time.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <libnotify/notify.h>
#include <gio/gunixoutputstream.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <dbus/dbus-glib.h>


#define TYPE_PASSWORD_DIALOG (password_dialog_get_type ())
#define PASSWORD_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PASSWORD_DIALOG, PasswordDialog))
#define PASSWORD_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PASSWORD_DIALOG, PasswordDialogClass))
#define IS_PASSWORD_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PASSWORD_DIALOG))
#define IS_PASSWORD_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PASSWORD_DIALOG))
#define PASSWORD_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PASSWORD_DIALOG, PasswordDialogClass))

typedef struct _PasswordDialog PasswordDialog;
typedef struct _PasswordDialogClass PasswordDialogClass;
typedef struct _PasswordDialogPrivate PasswordDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_MY_STATUS_ICON (my_status_icon_get_type ())
#define MY_STATUS_ICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_STATUS_ICON, MyStatusIcon))
#define MY_STATUS_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_STATUS_ICON, MyStatusIconClass))
#define IS_MY_STATUS_ICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_STATUS_ICON))
#define IS_MY_STATUS_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_STATUS_ICON))
#define MY_STATUS_ICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_STATUS_ICON, MyStatusIconClass))

typedef struct _MyStatusIcon MyStatusIcon;
typedef struct _MyStatusIconClass MyStatusIconClass;
typedef struct _MyStatusIconPrivate MyStatusIconPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _PasswordDialog {
	GtkDialog parent_instance;
	PasswordDialogPrivate * priv;
	GtkEntry* entry;
};

struct _PasswordDialogClass {
	GtkDialogClass parent_class;
};

struct _MyStatusIcon {
	GtkStatusIcon parent_instance;
	MyStatusIconPrivate * priv;
};

struct _MyStatusIconClass {
	GtkStatusIconClass parent_class;
};

struct _MyStatusIconPrivate {
	GFile* directory;
	GFile* current;
	GFileMonitor* file_monitor;
	char* message;
	char* icon;
	char* socket;
	PasswordDialog* password_dialog;
};


static gpointer password_dialog_parent_class = NULL;
static gpointer my_status_icon_parent_class = NULL;

gint clock_gettime (gint id, struct timespec* ts);
GType password_dialog_get_type (void) G_GNUC_CONST;
enum  {
	PASSWORD_DIALOG_DUMMY_PROPERTY
};
PasswordDialog* password_dialog_new (const char* message, const char* icon);
PasswordDialog* password_dialog_construct (GType object_type, const char* message, const char* icon);
void password_dialog_on_entry_activated (PasswordDialog* self);
static void _password_dialog_on_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void password_dialog_finalize (GObject* obj);
GType my_status_icon_get_type (void) G_GNUC_CONST;
#define MY_STATUS_ICON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MY_STATUS_ICON, MyStatusIconPrivate))
enum  {
	MY_STATUS_ICON_DUMMY_PROPERTY
};
MyStatusIcon* my_status_icon_new (GError** error);
MyStatusIcon* my_status_icon_construct (GType object_type, GError** error);
static void my_status_icon_file_monitor_changed (MyStatusIcon* self, GFile* file, GFile* other_file, GFileMonitorEvent event_type, GError** error);
static void _my_status_icon_file_monitor_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self, GError** error);
static void my_status_icon_look_for_password (MyStatusIcon* self, GError** error);
static void my_status_icon_status_icon_activate (MyStatusIcon* self, GError** error);
static void _my_status_icon_status_icon_activate_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self, GError** error);
static gboolean my_status_icon_load_password (MyStatusIcon* self, GError** error);
static void my_status_icon_finalize (GObject* obj);
void show_error (const char* e);
gint _vala_main (char** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

const GOptionEntry entries[1] = {{NULL}};


/***
  This file is part of systemd.

  Copyright 2010 Lennart Poettering

  systemd is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  systemd is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with systemd; If not, see <http://www.gnu.org/licenses/>.
***/
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 69 "ask-password-agent.vala"
static void _password_dialog_on_entry_activated_gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 136 "ask-password-agent.c"
	password_dialog_on_entry_activated (self);
}


#line 34 "ask-password-agent.vala"
PasswordDialog* password_dialog_construct (GType object_type, const char* message, const char* icon) {
#line 143 "ask-password-agent.c"
	PasswordDialog * self;
	GtkContainer* content;
	GtkBox* hbox;
	GtkImage* image;
	GtkBox* vbox;
	GtkLabel* label;
	GtkEntry* _tmp0_;
#line 34 "ask-password-agent.vala"
	g_return_val_if_fail (message != NULL, NULL);
#line 34 "ask-password-agent.vala"
	g_return_val_if_fail (icon != NULL, NULL);
#line 155 "ask-password-agent.c"
	self = g_object_newv (object_type, 0, NULL);
#line 35 "ask-password-agent.vala"
	gtk_window_set_title ((GtkWindow*) self, "System Password");
#line 36 "ask-password-agent.vala"
	gtk_dialog_set_has_separator ((GtkDialog*) self, FALSE);
#line 37 "ask-password-agent.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 8);
#line 38 "ask-password-agent.vala"
	gtk_dialog_set_default_response ((GtkDialog*) self, (gint) GTK_RESPONSE_OK);
#line 39 "ask-password-agent.vala"
	gtk_window_set_icon_name ((GtkWindow*) self, icon);
#line 41 "ask-password-agent.vala"
	gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CANCEL, (gint) GTK_RESPONSE_CANCEL);
#line 42 "ask-password-agent.vala"
	gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_OK, (gint) GTK_RESPONSE_OK);
#line 44 "ask-password-agent.vala"
	content = _g_object_ref0 (GTK_CONTAINER (gtk_dialog_get_content_area ((GtkDialog*) self)));
#line 46 "ask-password-agent.vala"
	hbox = (GtkBox*) g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 16));
#line 47 "ask-password-agent.vala"
	gtk_container_set_border_width ((GtkContainer*) hbox, (guint) 8);
#line 48 "ask-password-agent.vala"
	gtk_container_add (content, (GtkWidget*) hbox);
#line 50 "ask-password-agent.vala"
	image = g_object_ref_sink ((GtkImage*) gtk_image_new_from_icon_name (icon, GTK_ICON_SIZE_DIALOG));
#line 51 "ask-password-agent.vala"
	gtk_box_pack_start (hbox, (GtkWidget*) image, FALSE, FALSE, 0);
#line 53 "ask-password-agent.vala"
	vbox = (GtkBox*) g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 8));
#line 54 "ask-password-agent.vala"
	gtk_box_pack_start (hbox, (GtkWidget*) vbox, TRUE, TRUE, 0);
#line 56 "ask-password-agent.vala"
	label = g_object_ref_sink ((GtkLabel*) gtk_label_new (message));
#line 57 "ask-password-agent.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) label, FALSE, FALSE, 0);
#line 59 "ask-password-agent.vala"
	self->entry = (_tmp0_ = g_object_ref_sink ((GtkEntry*) gtk_entry_new ()), _g_object_unref0 (self->entry), _tmp0_);
#line 60 "ask-password-agent.vala"
	gtk_entry_set_visibility (self->entry, FALSE);
#line 61 "ask-password-agent.vala"
	gtk_entry_set_activates_default (self->entry, TRUE);
#line 62 "ask-password-agent.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) self->entry, FALSE, FALSE, 0);
#line 64 "ask-password-agent.vala"
	g_signal_connect_object (self->entry, "activate", (GCallback) _password_dialog_on_entry_activated_gtk_entry_activate, self, 0);
#line 66 "ask-password-agent.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 203 "ask-password-agent.c"
	_g_object_unref0 (label);
	_g_object_unref0 (vbox);
	_g_object_unref0 (image);
	_g_object_unref0 (hbox);
	_g_object_unref0 (content);
	return self;
}


#line 34 "ask-password-agent.vala"
PasswordDialog* password_dialog_new (const char* message, const char* icon) {
#line 34 "ask-password-agent.vala"
	return password_dialog_construct (TYPE_PASSWORD_DIALOG, message, icon);
#line 217 "ask-password-agent.c"
}


#line 69 "ask-password-agent.vala"
void password_dialog_on_entry_activated (PasswordDialog* self) {
#line 69 "ask-password-agent.vala"
	g_return_if_fail (self != NULL);
#line 70 "ask-password-agent.vala"
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_OK);
#line 227 "ask-password-agent.c"
}


static void password_dialog_class_init (PasswordDialogClass * klass) {
	password_dialog_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = password_dialog_finalize;
}


static void password_dialog_instance_init (PasswordDialog * self) {
}


static void password_dialog_finalize (GObject* obj) {
	PasswordDialog * self;
	self = PASSWORD_DIALOG (obj);
	_g_object_unref0 (self->entry);
	G_OBJECT_CLASS (password_dialog_parent_class)->finalize (obj);
}


GType password_dialog_get_type (void) {
	static volatile gsize password_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&password_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PasswordDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) password_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PasswordDialog), 0, (GInstanceInitFunc) password_dialog_instance_init, NULL };
		GType password_dialog_type_id;
		password_dialog_type_id = g_type_register_static (GTK_TYPE_DIALOG, "PasswordDialog", &g_define_type_info, 0);
		g_once_init_leave (&password_dialog_type_id__volatile, password_dialog_type_id);
	}
	return password_dialog_type_id__volatile;
}


#line 100 "ask-password-agent.vala"
static void _my_status_icon_file_monitor_changed_g_file_monitor_changed (GFileMonitor* _sender, GFile* file, GFile* other_file, GFileMonitorEvent event_type, gpointer self, GError** error) {
#line 263 "ask-password-agent.c"
	my_status_icon_file_monitor_changed (self, file, other_file, event_type, error);
}


#line 192 "ask-password-agent.vala"
static void _my_status_icon_status_icon_activate_gtk_status_icon_activate (GtkStatusIcon* _sender, gpointer self, GError** error) {
#line 270 "ask-password-agent.c"
	my_status_icon_status_icon_activate (self, error);
}


#line 86 "ask-password-agent.vala"
MyStatusIcon* my_status_icon_construct (GType object_type, GError** error) {
#line 277 "ask-password-agent.c"
	MyStatusIcon * self;
	GFile* _tmp0_;
	GFileMonitor* _tmp1_;
	GFileMonitor* _tmp2_;
	GFile* _tmp3_;
	GError * _inner_error_ = NULL;
#line 87 "ask-password-agent.vala"
	self = (MyStatusIcon*) g_object_new (object_type, "icon-name", "dialog-password", NULL);
#line 88 "ask-password-agent.vala"
	gtk_status_icon_set_title ((GtkStatusIcon*) self, "System Password");
#line 90 "ask-password-agent.vala"
	self->priv->directory = (_tmp0_ = g_file_new_for_path ("/dev/.systemd/ask-password/"), _g_object_unref0 (self->priv->directory), _tmp0_);
#line 91 "ask-password-agent.vala"
	_tmp1_ = g_file_monitor_directory (self->priv->directory, 0, NULL, &_inner_error_);
#line 292 "ask-password-agent.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (self);
		return NULL;
	}
#line 91 "ask-password-agent.vala"
	self->priv->file_monitor = (_tmp2_ = _tmp1_, _g_object_unref0 (self->priv->file_monitor), _tmp2_);
#line 92 "ask-password-agent.vala"
	g_signal_connect_object (self->priv->file_monitor, "changed", (GCallback) _my_status_icon_file_monitor_changed_g_file_monitor_changed, self, 0);
#line 94 "ask-password-agent.vala"
	self->priv->current = (_tmp3_ = NULL, _g_object_unref0 (self->priv->current), _tmp3_);
#line 95 "ask-password-agent.vala"
	my_status_icon_look_for_password (self, &_inner_error_);
#line 306 "ask-password-agent.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (self);
		return NULL;
	}
#line 97 "ask-password-agent.vala"
	g_signal_connect_object ((GtkStatusIcon*) self, "activate", (GCallback) _my_status_icon_status_icon_activate_gtk_status_icon_activate, self, 0);
#line 314 "ask-password-agent.c"
	return self;
}


#line 86 "ask-password-agent.vala"
MyStatusIcon* my_status_icon_new (GError** error) {
#line 86 "ask-password-agent.vala"
	return my_status_icon_construct (TYPE_MY_STATUS_ICON, error);
#line 323 "ask-password-agent.c"
}


#line 100 "ask-password-agent.vala"
static void my_status_icon_file_monitor_changed (MyStatusIcon* self, GFile* file, GFile* other_file, GFileMonitorEvent event_type, GError** error) {
#line 329 "ask-password-agent.c"
	char* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_ = FALSE;
	GError * _inner_error_ = NULL;
#line 100 "ask-password-agent.vala"
	g_return_if_fail (self != NULL);
#line 100 "ask-password-agent.vala"
	g_return_if_fail (file != NULL);
#line 102 "ask-password-agent.vala"
	if ((_tmp1_ = !g_str_has_prefix (_tmp0_ = g_file_get_basename (file), "ask."), _g_free0 (_tmp0_), _tmp1_)) {
#line 103 "ask-password-agent.vala"
		return;
#line 342 "ask-password-agent.c"
	}
#line 105 "ask-password-agent.vala"
	if (event_type == G_FILE_MONITOR_EVENT_CREATED) {
#line 105 "ask-password-agent.vala"
		_tmp2_ = TRUE;
#line 348 "ask-password-agent.c"
	} else {
#line 106 "ask-password-agent.vala"
		_tmp2_ = event_type == G_FILE_MONITOR_EVENT_DELETED;
#line 352 "ask-password-agent.c"
	}
#line 105 "ask-password-agent.vala"
	if (_tmp2_) {
#line 107 "ask-password-agent.vala"
		my_status_icon_look_for_password (self, &_inner_error_);
#line 358 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
	}
}


#line 110 "ask-password-agent.vala"
static void my_status_icon_look_for_password (MyStatusIcon* self, GError** error) {
#line 369 "ask-password-agent.c"
	GError * _inner_error_ = NULL;
#line 110 "ask-password-agent.vala"
	g_return_if_fail (self != NULL);
#line 112 "ask-password-agent.vala"
	if (self->priv->current != NULL) {
#line 113 "ask-password-agent.vala"
		if (!g_file_query_exists (self->priv->current, NULL)) {
#line 377 "ask-password-agent.c"
			GFile* _tmp0_;
#line 114 "ask-password-agent.vala"
			self->priv->current = (_tmp0_ = NULL, _g_object_unref0 (self->priv->current), _tmp0_);
#line 115 "ask-password-agent.vala"
			if (self->priv->password_dialog != NULL) {
#line 116 "ask-password-agent.vala"
				gtk_dialog_response ((GtkDialog*) self->priv->password_dialog, (gint) GTK_RESPONSE_REJECT);
#line 385 "ask-password-agent.c"
			}
		}
	}
#line 120 "ask-password-agent.vala"
	if (self->priv->current == NULL) {
#line 391 "ask-password-agent.c"
		GFileEnumerator* enumerator;
		GFileInfo* i;
#line 121 "ask-password-agent.vala"
		enumerator = g_file_enumerate_children (self->priv->directory, "standard::name", G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS, NULL, &_inner_error_);
#line 396 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			return;
		}
		i = NULL;
#line 124 "ask-password-agent.vala"
		while (TRUE) {
#line 404 "ask-password-agent.c"
			GFileInfo* _tmp1_;
			GFileInfo* _tmp2_;
			GFile* _tmp3_;
			gboolean _tmp4_;
			GFile* _tmp5_;
#line 124 "ask-password-agent.vala"
			_tmp1_ = g_file_enumerator_next_file (enumerator, NULL, &_inner_error_);
#line 412 "ask-password-agent.c"
			if (_inner_error_ != NULL) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (i);
				_g_object_unref0 (enumerator);
				return;
			}
#line 124 "ask-password-agent.vala"
			if (!((i = (_tmp2_ = _tmp1_, _g_object_unref0 (i), _tmp2_)) != NULL)) {
#line 124 "ask-password-agent.vala"
				break;
#line 423 "ask-password-agent.c"
			}
#line 125 "ask-password-agent.vala"
			if (!g_str_has_prefix (g_file_info_get_name (i), "ask.")) {
#line 126 "ask-password-agent.vala"
				continue;
#line 429 "ask-password-agent.c"
			}
#line 128 "ask-password-agent.vala"
			self->priv->current = (_tmp3_ = g_file_get_child (self->priv->directory, g_file_info_get_name (i)), _g_object_unref0 (self->priv->current), _tmp3_);
#line 130 "ask-password-agent.vala"
			_tmp4_ = my_status_icon_load_password (self, &_inner_error_);
#line 435 "ask-password-agent.c"
			if (_inner_error_ != NULL) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (i);
				_g_object_unref0 (enumerator);
				return;
			}
#line 130 "ask-password-agent.vala"
			if (_tmp4_) {
#line 131 "ask-password-agent.vala"
				break;
#line 446 "ask-password-agent.c"
			}
#line 133 "ask-password-agent.vala"
			self->priv->current = (_tmp5_ = NULL, _g_object_unref0 (self->priv->current), _tmp5_);
#line 450 "ask-password-agent.c"
		}
		_g_object_unref0 (i);
		_g_object_unref0 (enumerator);
	}
#line 137 "ask-password-agent.vala"
	if (self->priv->current == NULL) {
#line 138 "ask-password-agent.vala"
		gtk_status_icon_set_visible ((GtkStatusIcon*) self, FALSE);
#line 459 "ask-password-agent.c"
	}
}


#line 142 "ask-password-agent.vala"
static gboolean my_status_icon_load_password (MyStatusIcon* self, GError** error) {
#line 466 "ask-password-agent.c"
	gboolean result = FALSE;
	GKeyFile* key_file;
	NotifyNotification* n;
	GError * _inner_error_ = NULL;
#line 142 "ask-password-agent.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 144 "ask-password-agent.vala"
	key_file = g_key_file_new ();
#line 475 "ask-password-agent.c"
	{
		struct timespec ts = {0};
		char* _tmp0_;
		char* not_after_as_string;
		guint64 now;
		guint64 not_after = 0ULL;
		char* _tmp1_;
		char* _tmp2_;
#line 149 "ask-password-agent.vala"
		g_key_file_load_from_file (key_file, _tmp0_ = g_file_get_path (self->priv->current), G_KEY_FILE_NONE, &_inner_error_);
#line 486 "ask-password-agent.c"
		_g_free0 (_tmp0_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
#line 151 "ask-password-agent.vala"
		not_after_as_string = g_key_file_get_string (key_file, "Ask", "NotAfter", &_inner_error_);
#line 493 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
#line 153 "ask-password-agent.vala"
		clock_gettime (1, &ts);
#line 154 "ask-password-agent.vala"
		now = (guint64) ((ts.tv_sec * 1000000) + (ts.tv_nsec / 1000));
#line 157 "ask-password-agent.vala"
		if (sscanf (not_after_as_string, "%llu", &not_after) != 1) {
#line 503 "ask-password-agent.c"
			result = FALSE;
			_g_free0 (not_after_as_string);
			_g_key_file_free0 (key_file);
#line 158 "ask-password-agent.vala"
			return result;
#line 509 "ask-password-agent.c"
		}
#line 160 "ask-password-agent.vala"
		if (not_after < now) {
#line 513 "ask-password-agent.c"
			result = FALSE;
			_g_free0 (not_after_as_string);
			_g_key_file_free0 (key_file);
#line 161 "ask-password-agent.vala"
			return result;
#line 519 "ask-password-agent.c"
		}
#line 163 "ask-password-agent.vala"
		_tmp1_ = g_key_file_get_string (key_file, "Ask", "Socket", &_inner_error_);
#line 523 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			_g_free0 (not_after_as_string);
			goto __catch0_g_error;
		}
#line 163 "ask-password-agent.vala"
		self->priv->socket = (_tmp2_ = _tmp1_, _g_free0 (self->priv->socket), _tmp2_);
#line 530 "ask-password-agent.c"
		_g_free0 (not_after_as_string);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			result = FALSE;
			_g_error_free0 (e);
			_g_key_file_free0 (key_file);
#line 165 "ask-password-agent.vala"
			return result;
#line 545 "ask-password-agent.c"
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_key_file_free0 (key_file);
		return FALSE;
	}
	{
		char* _tmp3_;
		char* _tmp4_;
		char* _tmp5_;
#line 169 "ask-password-agent.vala"
		_tmp3_ = g_key_file_get_string (key_file, "Ask", "Message", &_inner_error_);
#line 560 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
#line 169 "ask-password-agent.vala"
		self->priv->message = (_tmp5_ = g_strcompress (_tmp4_ = _tmp3_), _g_free0 (self->priv->message), _tmp5_);
#line 566 "ask-password-agent.c"
		_g_free0 (_tmp4_);
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			char* _tmp6_;
#line 171 "ask-password-agent.vala"
			self->priv->message = (_tmp6_ = g_strdup ("Please Enter System Password!"), _g_free0 (self->priv->message), _tmp6_);
#line 579 "ask-password-agent.c"
			_g_error_free0 (e);
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_key_file_free0 (key_file);
		return FALSE;
	}
#line 173 "ask-password-agent.vala"
	gtk_status_icon_set_tooltip_text ((GtkStatusIcon*) self, self->priv->message);
#line 591 "ask-password-agent.c"
	{
		char* _tmp7_;
		char* _tmp8_;
#line 176 "ask-password-agent.vala"
		_tmp7_ = g_key_file_get_string (key_file, "Ask", "Icon", &_inner_error_);
#line 597 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
#line 176 "ask-password-agent.vala"
		self->priv->icon = (_tmp8_ = _tmp7_, _g_free0 (self->priv->icon), _tmp8_);
#line 603 "ask-password-agent.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			char* _tmp9_;
#line 178 "ask-password-agent.vala"
			self->priv->icon = (_tmp9_ = g_strdup ("dialog-password"), _g_free0 (self->priv->icon), _tmp9_);
#line 615 "ask-password-agent.c"
			_g_error_free0 (e);
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_key_file_free0 (key_file);
		return FALSE;
	}
#line 180 "ask-password-agent.vala"
	gtk_status_icon_set_from_icon_name ((GtkStatusIcon*) self, self->priv->icon);
#line 182 "ask-password-agent.vala"
	gtk_status_icon_set_visible ((GtkStatusIcon*) self, TRUE);
#line 184 "ask-password-agent.vala"
	n = notify_notification_new (gtk_status_icon_get_title ((GtkStatusIcon*) self), self->priv->message, self->priv->icon, NULL);
#line 185 "ask-password-agent.vala"
	notify_notification_attach_to_status_icon (n, (GtkStatusIcon*) self);
#line 186 "ask-password-agent.vala"
	notify_notification_set_timeout (n, 5000);
#line 187 "ask-password-agent.vala"
	notify_notification_show (n, &_inner_error_);
#line 637 "ask-password-agent.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (n);
		_g_key_file_free0 (key_file);
		return FALSE;
	}
	result = TRUE;
	_g_object_unref0 (n);
	_g_key_file_free0 (key_file);
#line 189 "ask-password-agent.vala"
	return result;
#line 649 "ask-password-agent.c"
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, -1);
#line 1166 "glib-2.0.vapi"
	return result;
#line 659 "ask-password-agent.c"
}


#line 192 "ask-password-agent.vala"
static void my_status_icon_status_icon_activate (MyStatusIcon* self, GError** error) {
#line 665 "ask-password-agent.c"
	PasswordDialog* _tmp0_;
	gint _result_;
	char* password;
	PasswordDialog* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gint to_process = 0;
	const char* _tmp3_;
	char** _tmp4_ = NULL;
	char** _tmp5_;
	gint _tmp5__length1;
	GOutputStream* stream;
	GError * _inner_error_ = NULL;
#line 192 "ask-password-agent.vala"
	g_return_if_fail (self != NULL);
#line 194 "ask-password-agent.vala"
	if (self->priv->current == NULL) {
#line 195 "ask-password-agent.vala"
		return;
#line 684 "ask-password-agent.c"
	}
#line 197 "ask-password-agent.vala"
	if (self->priv->password_dialog != NULL) {
#line 198 "ask-password-agent.vala"
		gtk_window_present ((GtkWindow*) self->priv->password_dialog);
#line 199 "ask-password-agent.vala"
		return;
#line 692 "ask-password-agent.c"
	}
#line 202 "ask-password-agent.vala"
	self->priv->password_dialog = (_tmp0_ = g_object_ref_sink (password_dialog_new (self->priv->message, self->priv->icon)), _g_object_unref0 (self->priv->password_dialog), _tmp0_);
#line 204 "ask-password-agent.vala"
	_result_ = gtk_dialog_run ((GtkDialog*) self->priv->password_dialog);
#line 205 "ask-password-agent.vala"
	password = g_strdup (gtk_entry_get_text (self->priv->password_dialog->entry));
#line 207 "ask-password-agent.vala"
	gtk_object_destroy ((GtkObject*) self->priv->password_dialog);
#line 208 "ask-password-agent.vala"
	self->priv->password_dialog = (_tmp1_ = NULL, _g_object_unref0 (self->priv->password_dialog), _tmp1_);
#line 210 "ask-password-agent.vala"
	if (_result_ == GTK_RESPONSE_REJECT) {
#line 210 "ask-password-agent.vala"
		_tmp2_ = TRUE;
#line 708 "ask-password-agent.c"
	} else {
#line 211 "ask-password-agent.vala"
		_tmp2_ = _result_ == GTK_RESPONSE_DELETE_EVENT;
#line 712 "ask-password-agent.c"
	}
#line 210 "ask-password-agent.vala"
	if (_tmp2_) {
#line 716 "ask-password-agent.c"
		_g_free0 (password);
#line 212 "ask-password-agent.vala"
		return;
#line 720 "ask-password-agent.c"
	}
	_tmp3_ = NULL;
#line 218 "ask-password-agent.vala"
	if (_result_ == GTK_RESPONSE_OK) {
#line 218 "ask-password-agent.vala"
		_tmp3_ = "1";
#line 727 "ask-password-agent.c"
	} else {
#line 218 "ask-password-agent.vala"
		_tmp3_ = "0";
#line 731 "ask-password-agent.c"
	}
#line 216 "ask-password-agent.vala"
	g_spawn_async_with_pipes (NULL, (_tmp5_ = (_tmp4_ = g_new0 (char*, 4 + 1), _tmp4_[0] = g_strdup ("/usr/bin/pkexec"), _tmp4_[1] = g_strdup ("/lib/systemd/systemd-reply-password"), _tmp4_[2] = g_strdup (_tmp3_), _tmp4_[3] = g_strdup (self->priv->socket), _tmp4_), _tmp5__length1 = 4, _tmp5_), NULL, 0, NULL, NULL, NULL, &to_process, NULL, NULL, &_inner_error_);
#line 735 "ask-password-agent.c"
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_free0 (password);
		return;
	}
#line 227 "ask-password-agent.vala"
	stream = (GOutputStream*) ((GUnixOutputStream*) g_unix_output_stream_new (to_process, TRUE));
#line 229 "ask-password-agent.vala"
	g_output_stream_write (stream, password, (gsize) string_get_length (password), NULL, &_inner_error_);
#line 746 "ask-password-agent.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_object_unref0 (stream);
		_g_free0 (password);
		return;
	}
	_g_object_unref0 (stream);
	_g_free0 (password);
}


static void my_status_icon_class_init (MyStatusIconClass * klass) {
	my_status_icon_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MyStatusIconPrivate));
	G_OBJECT_CLASS (klass)->finalize = my_status_icon_finalize;
}


static void my_status_icon_instance_init (MyStatusIcon * self) {
	self->priv = MY_STATUS_ICON_GET_PRIVATE (self);
}


static void my_status_icon_finalize (GObject* obj) {
	MyStatusIcon * self;
	self = MY_STATUS_ICON (obj);
	_g_object_unref0 (self->priv->directory);
	_g_object_unref0 (self->priv->current);
	_g_object_unref0 (self->priv->file_monitor);
	_g_free0 (self->priv->message);
	_g_free0 (self->priv->icon);
	_g_free0 (self->priv->socket);
	_g_object_unref0 (self->priv->password_dialog);
	G_OBJECT_CLASS (my_status_icon_parent_class)->finalize (obj);
}


GType my_status_icon_get_type (void) {
	static volatile gsize my_status_icon_type_id__volatile = 0;
	if (g_once_init_enter (&my_status_icon_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyStatusIconClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_status_icon_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyStatusIcon), 0, (GInstanceInitFunc) my_status_icon_instance_init, NULL };
		GType my_status_icon_type_id;
		my_status_icon_type_id = g_type_register_static (GTK_TYPE_STATUS_ICON, "MyStatusIcon", &g_define_type_info, 0);
		g_once_init_leave (&my_status_icon_type_id__volatile, my_status_icon_type_id);
	}
	return my_status_icon_type_id__volatile;
}


#line 237 "ask-password-agent.vala"
void show_error (const char* e) {
#line 798 "ask-password-agent.c"
	GtkMessageDialog* m;
#line 237 "ask-password-agent.vala"
	g_return_if_fail (e != NULL);
#line 238 "ask-password-agent.vala"
	m = g_object_ref_sink ((GtkMessageDialog*) gtk_message_dialog_new (NULL, 0, GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, "%s", e));
#line 239 "ask-password-agent.vala"
	gtk_dialog_run ((GtkDialog*) m);
#line 240 "ask-password-agent.vala"
	gtk_object_destroy ((GtkObject*) m);
#line 808 "ask-password-agent.c"
	_g_object_unref0 (m);
}


#line 243 "ask-password-agent.vala"
gint _vala_main (char** args, int args_length1) {
#line 815 "ask-password-agent.c"
	gint result = 0;
	GError * _inner_error_ = NULL;
	{
		MyStatusIcon* i;
#line 245 "ask-password-agent.vala"
		gtk_init_with_args (&args_length1, &args, "[OPTION...]", entries, "systemd-ask-password-agent", &_inner_error_);
#line 822 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch3_dbus_gerror;
			}
			goto __catch3_g_error;
		}
#line 246 "ask-password-agent.vala"
		notify_init ("Password Agent");
#line 248 "ask-password-agent.vala"
		i = my_status_icon_new (&_inner_error_);
#line 833 "ask-password-agent.c"
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == DBUS_GERROR) {
				goto __catch3_dbus_gerror;
			}
			goto __catch3_g_error;
		}
#line 249 "ask-password-agent.vala"
		gtk_main ();
#line 842 "ask-password-agent.c"
		_g_object_unref0 (i);
	}
	goto __finally3;
	__catch3_dbus_gerror:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
#line 252 "ask-password-agent.vala"
			show_error (e->message);
#line 854 "ask-password-agent.c"
			_g_error_free0 (e);
		}
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
#line 254 "ask-password-agent.vala"
			show_error (e->message);
#line 867 "ask-password-agent.c"
			_g_error_free0 (e);
		}
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
#line 257 "ask-password-agent.vala"
	return result;
#line 880 "ask-password-agent.c"
}


#line 243 "ask-password-agent.vala"
int main (int argc, char ** argv) {
#line 243 "ask-password-agent.vala"
	g_type_init ();
#line 243 "ask-password-agent.vala"
	return _vala_main (argv, argc);
#line 890 "ask-password-agent.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}




